# Generated by Django 5.0.7 on 2024-08-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_management_features', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='community',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='community',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='communityresource',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='communityresource',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='updated_at',
        ),
    ]
