# Generated by Django 5.0.7 on 2024-08-02 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0002_remove_interaction_details_remove_interaction_id_and_more'),
        ('sales_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='property_preferences',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='salesclientinteraction',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='salesclientinteraction',
            name='clientinteraction_ptr',
        ),
        migrations.AddField(
            model_name='lead',
            name='client_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client_management.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesclientinteraction',
            name='interaction_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client_management.interaction'),
            preserve_default=False,
        ),
    ]
