# Generated by Django 5.0.7 on 2024-08-05 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_name_user_first_name_user_credit_card_number_and_more'),
        ('sales_management', '0002_remove_lead_agent_remove_lead_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='status',
            new_name='lead_status',
        ),
        migrations.AddField(
            model_name='lead',
            name='note',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('office', 'Office'), ('apartment', 'Apartment')], default='house', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('search_web', 'Search Web'), ('tik_tok', 'Tik Tok')], default='search_web', max_length=50),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('content_of_deal', models.TextField(max_length=2000)),
                ('description', models.TextField(max_length=2000)),
                ('is_approved', models.BooleanField(default=False)),
                ('deal_type', models.CharField(choices=[('rent', 'Rent'), ('sell', 'Sell')], default='rent')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_management.lead')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
    ]
