# Generated by Django 5.0.7 on 2024-08-14 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_portal'),
        ('property_listing', '0001_initial'),
        ('sales_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCaptureForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('form_fields', models.JSONField()),
                ('form_url', models.URLField()),
                ('customization_options', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('assignment', models.AutoField(primary_key=True, serialize=False)),
                ('criteria', models.JSONField()),
                ('assignment_date', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_listing.realestateagent')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_management.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadCommunication',
            fields=[
                ('communication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.communication')),
                ('communication_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('call', 'Call')], default='email', max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Complted'), ('pending', 'Pending')], default='pending', max_length=255)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_listing.realestateagent')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_management.lead')),
            ],
            bases=('core.communication',),
        ),
        migrations.CreateModel(
            name='LeadNurturing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('communication_tools', models.JSONField()),
                ('follow_up_actions', models.JSONField()),
                ('engagement_metrics', models.JSONField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_management.lead')),
            ],
        ),
        migrations.CreateModel(
            name='OfflineLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('event_details', models.TextField()),
                ('contact_information', models.JSONField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_management.lead')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter')], default='facebook', max_length=255)),
                ('campaign_id', models.CharField(max_length=255)),
                ('ad_creative', models.CharField(max_length=255)),
                ('engagement_metrics', models.JSONField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_management.lead')),
            ],
        ),
    ]
