# Generated by Django 5.0.7 on 2024-08-16 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_feedback'),
        ('visitor_management_for_property_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorFeedback',
            fields=[
                ('feedback_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.feedback')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_management_for_property_access.visitorproperty')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_management_for_property_access.visitor')),
            ],
            bases=('core.feedback',),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
