# Generated by Django 5.0.7 on 2024-08-12 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_portal'),
        ('lease_rental_management', '0001_initial'),
        ('tenant_portal_development', '0002_alter_tenantnotification_delivery_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPortal',
            fields=[
                ('portal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.portal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease_rental_management.tenant')),
            ],
            bases=('core.portal',),
        ),
        migrations.DeleteModel(
            name='Portal',
        ),
    ]
