# Generated by Django 5.0.7 on 2024-08-08 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectiveBuyerRenter',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('preferences', models.JSONField()),
            ],
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='RealEstateAgent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
            ],
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='PropertyNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.notification')),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            bases=('core.notification',),
        ),
        migrations.CreateModel(
            name='ThePropertyListing',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.property')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_listing.realestateagent')),
            ],
            bases=('core.property',),
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_listing.prospectivebuyerrenter')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_listing.thepropertylisting')),
            ],
        ),
        migrations.AddField(
            model_name='realestateagent',
            name='listings',
            field=models.ManyToManyField(related_name='agent_listings', to='property_listing.thepropertylisting'),
        ),
        migrations.AddField(
            model_name='prospectivebuyerrenter',
            name='saved_listings',
            field=models.ManyToManyField(related_name='saved_by', to='property_listing.thepropertylisting'),
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('properties', models.ManyToManyField(related_name='owner_properties', to='property_listing.thepropertylisting')),
            ],
            bases=('core.user',),
        ),
    ]
