# Generated by Django 5.0.7 on 2024-08-21 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bank_partnership', models.CharField(max_length=255)),
                ('founding_date', models.DateField()),
                ('bank_code', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('website_link', models.URLField()),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='realestateagent',
            name='listings',
        ),
        migrations.AddField(
            model_name='realestateagent',
            name='agency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='agent_agency', to='property_listing.agency'),
            preserve_default=False,
        ),
    ]
