# Generated by Django 5.0.7 on 2024-08-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0002_agency_remove_realestateagent_listings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedlisting',
            name='created_at',
        ),
    ]
