# Generated by Django 5.0.7 on 2024-08-12 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_calendar_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calendar', models.JSONField(default=dict)),
                ('reminders', models.JSONField(default=list)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_calendar_management.task')),
            ],
        ),
    ]
