# Generated by Django 5.0.7 on 2024-08-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_propertylisting_badroom_number_and_more'),
        ('task_calendar_management', '0002_alter_calendarintegration_sync_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meeting',
            new_name='Event',
        ),
    ]
