services:
  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    ports:
      - "${POSTGRESQL_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: