# Generated by Django 5.0.7 on 2024-08-10 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('terms', models.JSONField(default=dict)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('signed_document', models.URLField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_agreements', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyManager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('lease_agreements', models.ManyToManyField(related_name='property_managers', to='lease_rental_management.leaseagreement')),
                ('properties', models.ManyToManyField(related_name='managers', to='core.property')),
            ],
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('payment_history', models.JSONField(default=list)),
                ('lease_agreements', models.ManyToManyField(related_name='tenants', to='lease_rental_management.leaseagreement')),
            ],
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('lease_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease_rental_management.leaseagreement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease_rental_management.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseRentalCommunication',
            fields=[
                ('communication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.communication')),
                ('type', models.CharField(max_length=50)),
                ('response', models.TextField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease_rental_management.propertymanager')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease_rental_management.tenant')),
            ],
            bases=('core.communication',),
        ),
    ]
