# Generated by Django 5.0.7 on 2024-08-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_with_accounting_software', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='export',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='integrationpropertymanager',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='integrationpropertymanager',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='integrationsettings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='integrationsettings',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='integrationpropertymanager',
            name='financial_data',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
