# Generated by Django 5.0.7 on 2024-08-15 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_portal'),
        ('lease_rental_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('furniture', 'furniture'), ('appliances', 'Appliances'), ('electronics', 'Electronics')], default='furniture', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='new', max_length=50)),
                ('photos', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryProperty',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.property')),
                ('listing_type', models.CharField(choices=[('rental', 'Rental'), ('sale', 'Sale')], default='rental', max_length=50)),
                ('furnished', models.BooleanField(default=False)),
            ],
            bases=('core.property',),
        ),
        migrations.CreateModel(
            name='DepreciationRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('depreciation_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_depreciation_date', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_records', to='inventory_management.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.notification')),
                ('type', models.CharField(choices=[('maintenance', 'Maintenance'), ('reminder', 'Reminder'), ('inventory_update', 'Inventory Update')], max_length=100)),
                ('property_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease_rental_management.propertymanager')),
            ],
            bases=('core.notification',),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory_management.inventoryproperty'),
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.TextField()),
                ('service_provider', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='inventory_management.inventoryitem')),
            ],
        ),
    ]
