# Generated by Django 5.0.7 on 2024-08-13 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_portal'),
        ('lease_rental_management', '0001_initial'),
        ('property_listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerFinancialReport',
            fields=[
                ('financialreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.financialreport')),
                ('report_type', models.CharField(max_length=255)),
                ('document_url', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_listing.propertyowner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
            bases=('core.financialreport',),
        ),
        migrations.CreateModel(
            name='OwnerNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.notification')),
                ('notification_type', models.CharField(max_length=255)),
                ('delivery_method', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_listing.propertyowner')),
            ],
            bases=('core.notification',),
        ),
        migrations.CreateModel(
            name='OwnerPortal',
            fields=[
                ('portal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.portal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_listing.propertyowner')),
            ],
            bases=('core.portal',),
        ),
        migrations.CreateModel(
            name='OwnerResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.resource')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_listing.propertyowner')),
            ],
            bases=('core.resource',),
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=255)),
                ('occupancy_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rental_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_listing.propertyowner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='PortalCommunication',
            fields=[
                ('communication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.communication')),
                ('attachments', models.JSONField(default=list)),
                ('communication_log', models.TextField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease_rental_management.propertymanager')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_listing.propertyowner')),
            ],
            bases=('core.communication',),
        ),
    ]
