# Generated by Django 5.0.7 on 2024-08-07 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_rental_management', '0001_initial'),
        ('maintenance_and_service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancepropertymanager',
            name='property_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_managers', to='lease_rental_management.propertymanager'),
        ),
    ]
