# Generated by Django 5.0.7 on 2024-08-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_and_service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetechnician',
            name='skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
