# Generated by Django 5.0.7 on 2024-08-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_and_service_requests', '0002_alter_maintenancepropertymanager_property_manager'),
        ('rental_lease_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancepropertymanager',
            name='property_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_managers', to='rental_lease_management.propertymanager'),
        ),
    ]
