# Generated by Django 5.0.7 on 2024-08-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_rental_management', '0001_initial'),
        ('maintenance_and_service_requests', '0002_alter_maintenancepropertymanager_property_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='manager',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='lease_rental_management.propertymanager'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='lease_rental_management.tenant'),
        ),
        migrations.AlterField(
            model_name='tenantrequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_requests', to='lease_rental_management.tenant'),
        ),
    ]
