# Generated by Django 5.0.7 on 2024-08-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_and_service_requests', '0002_maintenancetechnician_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerequest',
            old_name='updated_at',
            new_name='completion_date',
        ),
        migrations.RenameField(
            model_name='maintenancerequest',
            old_name='created_at',
            new_name='submission_date',
        ),
    ]
