# Generated by Django 5.0.7 on 2024-08-19 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_alter_user_user_type'),
        ('lease_rental_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('certifications', models.JSONField()),
            ],
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('under_construction', 'Under Construction'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='planning', max_length=50)),
                ('inspection_reports', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inspection_date', models.DateField()),
                ('findings', models.TextField()),
                ('compliance_status', models.CharField(max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_property_monitoring.inspector')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('HVAC_system', 'HVAC System'), ('water_heater', 'Water Heater'), ('electrical_panel', 'Electrical Panel')], default='HVAC_system', max_length=255)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('malfunctioning', 'Malfunctioning')], default='operational', max_length=50)),
                ('last_maintenance_date', models.DateField()),
                ('performance_metrics', models.JSONField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.AddField(
            model_name='inspector',
            name='assigned_projects',
            field=models.ManyToManyField(to='remote_property_monitoring.project'),
        ),
        migrations.CreateModel(
            name='ConstructionMonitoring',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('camera_feeds', models.JSONField()),
                ('progress_photos', models.JSONField()),
                ('safety_compliance_checklists', models.JSONField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_property_monitoring.project')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('camera', 'Camera'), ('motion', 'Motion'), ('sensor', 'Sensor'), ('door/window_sensor', 'Door/Window Sensor'), ('smart_lock', 'Smart Lock')], default='camera', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=50)),
                ('last_maintenance_date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='TenantMaintenanceRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[(' submitted', ' submitted'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=50)),
                ('attachments', models.JSONField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease_rental_management.tenant')),
            ],
        ),
    ]
