# Generated by Django 5.0.7 on 2024-08-28 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_remove_feedback_created_at_and_more'),
        ('remote_property_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionreport',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inspectionreport',
            name='inspection_date',
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='report_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.report'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TenantMaintenanceRequest',
        ),
    ]
