# Generated by Django 5.0.7 on 2024-08-20 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('lease_rental_management', '0001_initial'),
        ('predictive_analytics_for_market_insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audit_date', models.DateField()),
                ('audit_results', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('follow_up_required', 'Follow-up Required')], default='pending', max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyDashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('energy_consumption', models.FloatField()),
                ('cost_metrics', models.FloatField()),
                ('historical_trends', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyGoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_value', models.FloatField()),
                ('benchmark', models.CharField(max_length=255)),
                ('current_value', models.FloatField()),
                ('status', models.CharField(choices=[('met', 'Met'), ('not_met', 'Not Met'), ('in_progress', 'In Progress')], default='in_progress', max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyModelingTool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('building_design', models.JSONField()),
                ('energy_performance', models.FloatField()),
                ('roi_projections', models.FloatField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictive_analytics_for_market_insights.realestatedeveloper')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyMonitoringDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('smart_meter', 'Smart Meter'), ('energy_sensor', 'Energy Sensor')], default='smart_meter', max_length=255)),
                ('installation_date', models.DateField()),
                ('last_maintenance_date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_type', models.CharField(choices=[('lighting_upgrade', 'Lighting Upgrade'), ('HVAC_optimization', 'HVAC Optimization')], default='lighting_upgrade', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=50)),
                ('impact_metrics', models.JSONField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease_rental_management.propertymanager')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyRecommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recommendation_text', models.TextField()),
                ('category', models.CharField(choices=[('thermostat_setting', 'Thermostat Setting'), ('lighting_optimization', 'Lighting Optimization')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease_rental_management.tenant')),
            ],
        ),
    ]
