# Generated by Django 5.0.7 on 2024-08-20 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingCampaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=255)),
                ('target_audience', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bidding_strategy', models.CharField(max_length=255)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('cpa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingProperty',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.property')),
                ('virtual_tours', models.JSONField(blank=True, null=True)),
                ('media_optimization_recommendations', models.TextField(blank=True, null=True)),
            ],
            bases=('core.property',),
        ),
        migrations.CreateModel(
            name='MarketingAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('cpl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_reports', models.JSONField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_tools_integration.advertisingcampaign')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_tools_integration.marketingproperty')),
            ],
        ),
        migrations.CreateModel(
            name='ListingDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=255)),
                ('target_audience', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('views', models.IntegerField(default=0)),
                ('inquiries', models.IntegerField(default=0)),
                ('engagement_metrics', models.JSONField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_tools_integration.marketingproperty')),
            ],
        ),
        migrations.AddField(
            model_name='advertisingcampaign',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_tools_integration.marketingproperty'),
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
                ('engagement_metrics', models.JSONField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_tools_integration.marketingproperty')),
            ],
        ),
    ]
