# Generated by Django 5.0.7 on 2024-08-20 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('lease_rental_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySustainabilityRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_type', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('issued_by', models.CharField(max_length=255)),
                ('issued_date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilityCertification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certification_type', models.CharField(choices=[('leed', 'Leed'), ('energy_star', 'Energy_start')], default='leed', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('achieved', 'Achieved')], default='pending', max_length=255)),
                ('submission_deadline', models.DateField()),
                ('documentation', models.JSONField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilityDashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('energy_consumption', models.JSONField()),
                ('water_usage', models.JSONField()),
                ('waste_generation', models.JSONField()),
                ('ghg_emissions', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilityForum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='forums', to='lease_rental_management.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilityInitiative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('implementation_date', models.DateField()),
                ('resource_savings', models.JSONField()),
                ('environmental_impact', models.JSONField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='TenantSustainabilityResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.resource')),
                ('category', models.CharField(choices=[('energy_conservation', 'Energy Conservation'), ('waste_reduction', 'Waste Reduction')], default='energy_conservation', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease_rental_management.tenant')),
            ],
            bases=('core.resource',),
        ),
    ]
