# Generated by Django 5.0.7 on 2024-08-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_portal'),
        ('financial_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TenantPortal',
            new_name='FinancialPortal',
        ),
    ]
