# Generated by Django 5.0.7 on 2024-08-16 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.document')),
                ('signer_list', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('completed', 'Completed')], default='pending', max_length=50)),
            ],
            bases=('core.document',),
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('signature', models.TextField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_signing.signingdocument')),
            ],
        ),
        migrations.CreateModel(
            name='SignatureTracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('overdue', 'Overdue')], max_length=50)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_signing.signer')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_signing.signingdocument')),
            ],
        ),
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regulation', models.CharField(max_length=100)),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-compliant')], default='Non-compliant', max_length=50)),
                ('last_checked', models.DateTimeField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_signing.signingdocument')),
            ],
        ),
        migrations.CreateModel(
            name='SigningNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.notification')),
                ('type', models.CharField(choices=[('signature', 'Signature'), ('request', 'Request'), ('reminder', 'Reminder')], default='signature', max_length=50)),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=50)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_signing.signingdocument')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_signing.signer')),
            ],
            bases=('core.notification',),
        ),
    ]
