# Generated by Django 5.0.7 on 2024-08-20 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('lease_rental_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTrendAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=255)),
                ('trend_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictiveAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_source', models.CharField(max_length=255)),
                ('algorithm', models.CharField(max_length=255)),
                ('parameters', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentDashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('predicted_values', models.JSONField()),
                ('investment_returns', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyValuationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('predicted_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('growth_factors', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateDeveloper',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('projects', models.JSONField()),
                ('investment_strategies', models.JSONField()),
                ('market_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictive_analytics_for_market_insights.markettrendanalysis')),
            ],
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='DevelopmentFeasibilityTool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_parameters', models.JSONField()),
                ('roi_projections', models.JSONField()),
                ('risk_factors', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictive_analytics_for_market_insights.realestatedeveloper')),
            ],
        ),
        migrations.CreateModel(
            name='RentalDemandForecast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('demand_projections', models.JSONField()),
                ('tenant_preferences', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease_rental_management.propertymanager')),
            ],
        ),
        migrations.AddField(
            model_name='realestatedeveloper',
            name='demand_forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictive_analytics_for_market_insights.rentaldemandforecast'),
        ),
    ]
