# Generated by Django 5.0.7 on 2024-08-17 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_feedback'),
        ('lease_rental_management', '0001_initial'),
        ('property_listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTrendAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=255)),
                ('trend_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictiveAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_source', models.CharField(max_length=255)),
                ('algorithm', models.CharField(max_length=255)),
                ('parameters', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevelopmentFeasibilityTool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_parameters', models.JSONField()),
                ('roi_projections', models.JSONField()),
                ('risk_factors', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_listing.realestateagent')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentDashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('predicted_values', models.JSONField()),
                ('investment_returns', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyValuationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('predicted_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('growth_factors', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='RentalDemandForecast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('demand_projections', models.JSONField()),
                ('tenant_preferences', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease_rental_management.propertymanager')),
            ],
        ),
    ]
