# Generated by Django 5.0.7 on 2024-08-18 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_user_type'),
        ('predictive_analytics_for_market_insights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developmentfeasibilitytool',
            name='agent',
        ),
        migrations.CreateModel(
            name='RealEstateDeveloper',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('projects', models.JSONField()),
                ('investment_strategies', models.JSONField()),
                ('demand_forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictive_analytics_for_market_insights.rentaldemandforecast')),
                ('market_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictive_analytics_for_market_insights.markettrendanalysis')),
            ],
            bases=('core.user',),
        ),
        migrations.AddField(
            model_name='developmentfeasibilitytool',
            name='developer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='predictive_analytics_for_market_insights.realestatedeveloper'),
            preserve_default=False,
        ),
    ]
