# Generated by Django 5.0.7 on 2024-08-06 14:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseRentalAgreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('terms', models.JSONField(default=dict)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('signed_document', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseRentalTenant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('payment_history', models.JSONField(default=list)),
                ('lease_agreements', models.ManyToManyField(related_name='tenants', to='rental_lease_management.leaserentalagreement')),
            ],
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='PropertyManager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('lease_agreements', models.ManyToManyField(related_name='managers', to='rental_lease_management.leaserentalagreement')),
                ('properties', models.ManyToManyField(related_name='properties', to='core.property')),
            ],
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='LeaseRentalCommunication',
            fields=[
                ('communication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.communication')),
                ('type', models.CharField(max_length=50)),
                ('response', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_lease_management.leaserentaltenant')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_lease_management.propertymanager')),
            ],
            bases=('core.communication',),
        ),
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=20)),
                ('lease_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_lease_management.leaserentalagreement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_lease_management.leaserentaltenant')),
            ],
        ),
    ]
