# Generated by Django 5.0.7 on 2024-08-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_lease_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
