# Generated by Django 5.0.7 on 2024-08-02 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0001_initial'),
        ('core', '0003_alter_user_email_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='details',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='type',
        ),
        migrations.AddField(
            model_name='interaction',
            name='clientinteraction_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.clientinteraction'),
            preserve_default=False,
        ),
    ]
