# Generated by Django 5.0.7 on 2024-08-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0002_remove_interaction_details_remove_interaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_status',
            field=models.CharField(choices=[('new', 'New'), ('loyal', 'Loyal'), ('regular', 'Regular')], default='new', max_length=20),
        ),
    ]
