# Generated by Django 5.0.7 on 2024-08-10 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0002_clientreminder_delete_reminder'),
        ('core', '0003_reminder_alter_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientreminder',
            name='id',
        ),
        migrations.AlterField(
            model_name='clientreminder',
            name='reminder_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.reminder'),
        ),
    ]
