# Generated by Django 5.0.7 on 2024-08-09 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('lease_rental_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certifications', models.JSONField(default=list)),
                ('service_specialties', models.JSONField(default=list)),
                ('insurance_details', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('reviews', models.JSONField(default=list)),
                ('documents', models.JSONField(default=list)),
                ('pricing_model', models.CharField(max_length=50)),
                ('service_areas', models.JSONField(default=list)),
                ('availability', models.JSONField(default=dict)),
                ('profile_content', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('response_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resolution_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer_satisfaction_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('compliance_sla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feedback', models.JSONField(default=list)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_management.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorsPropertyManager',
            fields=[
                ('propertymanager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lease_rental_management.propertymanager')),
                ('managed_vendors', models.ManyToManyField(related_name='managed_by', to='vendor_management.vendor')),
            ],
            bases=('lease_rental_management.propertymanager',),
        ),
        migrations.CreateModel(
            name='VendorsCommunication',
            fields=[
                ('communication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.communication')),
                ('status', models.CharField(max_length=20)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='vendor_management.vendor')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='vendor_management.vendorspropertymanager')),
            ],
            bases=('core.communication',),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scope_of_work', models.TextField()),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_terms', models.TextField()),
                ('sla', models.TextField()),
                ('document_version', models.IntegerField(default=1)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_management.vendor')),
                ('property_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_management.vendorspropertymanager')),
            ],
        ),
    ]
