# Generated by Django 5.0.7 on 2024-08-20 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('task_calendar_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FairHousingCompliance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('training_module', models.TextField()),
                ('checklist', models.JSONField()),
                ('audit_trail', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocumentGenerator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=255)),
                ('template_content', models.TextField()),
                ('property_details', models.JSONField()),
                ('transaction_details', models.JSONField()),
                ('signatures', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RegulationRepository',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=255)),
                ('compliance_category', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceCalendar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reminders', models.JSONField(blank=True, null=True)),
                ('compliance_task', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_calendar_management.event')),
            ],
        ),
        migrations.CreateModel(
            name='DueDiligenceChecker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('check_type', models.CharField(max_length=255)),
                ('results', models.TextField()),
                ('risk_assessment', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
    ]
