# Generated by Django 5.0.7 on 2024-08-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_and_legal_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulationrepository',
            name='last_updated',
        ),
    ]
