# Generated by Django 5.0.7 on 2024-08-11 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProperty',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.property')),
                ('features', models.JSONField(default=list)),
                ('saved', models.BooleanField(default=False)),
            ],
            bases=('core.property',),
        ),
        migrations.CreateModel(
            name='CommunicationManager',
            fields=[
                ('communication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.communication')),
                ('notifications', models.JSONField(default=list)),
                ('inbox', models.JSONField(default=list)),
            ],
            bases=('core.communication',),
        ),
        migrations.CreateModel(
            name='MobileApp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('store_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MobileUserAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ssologin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationManager',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.notification')),
                ('user_preferences', models.JSONField(default=dict)),
            ],
            bases=('core.notification',),
        ),
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tasks', models.JSONField(default=list)),
                ('calendar', models.JSONField(default=dict)),
                ('reminders', models.JSONField(default=list)),
            ],
        ),
    ]
