# Generated by Django 5.0.7 on 2024-08-09 12:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInteraction',
            fields=[
                ('client_interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(max_length=50)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('communication_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('financial_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('financial_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('video', models.FileField(upload_to='videos/')),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bathroom_number', models.IntegerField(default=0)),
                ('badroom_number', models.IntegerField(default=0)),
                ('garage', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('swiming_pool', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year_built', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOpportunity',
            fields=[
                ('sales_opportunity_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cin', models.CharField(max_length=8)),
                ('birth_date', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('credit_card_number', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('lease_rental_tenant', 'Lease Rental Tenant'), ('property_owner', 'Property Owner'), ('property_manager', 'Property Manager'), ('vendor', 'Vendor'), ('prospective_buyer_renter', 'Prospective Buyer Renter'), ('real_estate_agent', 'Real Estate Agent'), ('prospective_tenant', 'Prospective Tenant')], default='client', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('agreement', 'Agreement'), ('deed', 'Deed'), ('lease', 'Lease'), ('inspection_report', 'Inspection Report'), ('insurance_policy', 'Insurance Policy')], default='contract', max_length=50)),
                ('file_path', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=10)),
                ('access_permissions', models.JSONField(default=dict)),
                ('expiration_date', models.DateField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
