# Generated by Django 5.0.7 on 2024-08-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
