# Generated by Django 5.0.7 on 2024-08-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('contract', 'Contract'), ('agreement', 'Agreement'), ('deed', 'Deed'), ('lease', 'Lease'), ('addendum', 'Addentum'), ('inspection_report', 'Inspection Report'), ('insurance_policy', 'Insurance Policy')], default='contract', max_length=50),
        ),
    ]
