# Generated by Django 5.0.7 on 2024-08-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_propertylisting_address_propertylisting_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('lease_rental_tenant', 'Lease Rental Tenant'), ('property_owner', 'Property Owner'), ('property_manager', 'Property Manager'), ('prospective_buyer_renter', 'Prospective Buyer Renter'), ('real_estate_agent', 'Real Estate Agent')], default='client', max_length=50),
        ),
    ]
