# Generated by Django 5.0.7 on 2024-08-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminder_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_content', models.TextField()),
                ('reminder_date', models.DateTimeField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quartly', 'Quartly'), ('bi-annually', 'Bi-annually'), ('annually', 'Annually')], default='daily', max_length=50)),
                ('delivary_channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_platform_alert', 'In-platform Alert')], default='email', max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent')], default='scheduled', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed_use', 'Mixed Use'), ('land', 'Land'), ('special_purpose', 'Special Purpose'), ('investment', 'Investment'), ('luxury', 'Luxury'), ('recreational', 'Recreational'), ('development', 'Development')], default='residential', max_length=50),
        ),
    ]
