# Generated by Django 5.0.7 on 2024-08-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cin',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
