# Generated by Django 5.0.7 on 2024-08-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('portal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
