# Generated by Django 5.0.7 on 2024-08-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_name_user_first_name_user_credit_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='badroom_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='bathroom_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='swiming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='year_built',
            field=models.DateField(auto_now=True),
        ),
    ]
