# Generated by Django 5.0.7 on 2024-08-10 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_management', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMClientSegmentation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('segment_name', models.CharField(max_length=100)),
                ('criteria', models.TextField()),
                ('client_list', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CRMIntegration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crm_tool', models.CharField(choices=[('salesforce', 'Salesforce'), ('hubSpot', 'HubSpot')], default='salesforce', max_length=100)),
                ('api_key', models.CharField(max_length=255)),
                ('sync_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('failed', 'Failed')], default='paused', max_length=50)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CRMIntegrationSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crm_tool', models.CharField(max_length=100)),
                ('custom_fields', models.JSONField()),
                ('sync_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='hourly', max_length=50)),
                ('notification_settings', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CRMClientInteraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting')], default='call', max_length=50)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.client')),
            ],
        ),
        migrations.CreateModel(
            name='CRMClientSync',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crm_client_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sync_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('failed', 'Failed')], default='paused', max_length=50)),
                ('last_update_time', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.client')),
            ],
        ),
        migrations.CreateModel(
            name='CRMSalesOpportunity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crm_opportunity_id', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
    ]
