# Generated by Django 5.0.7 on 2024-08-09 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.document')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
            bases=('core.document',),
        ),
        migrations.CreateModel(
            name='ESignatureIntegration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('signature_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_log', models.JSONField(default=list)),
                ('signing_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_management.propertydocument')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_management.propertydocument')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSharing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('access_permissions', models.JSONField(default=dict)),
                ('activity_log', models.JSONField(default=list)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_management.propertydocument')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentExpirationReminder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reminder_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], default='pending', max_length=50)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_management.propertydocument')),
            ],
        ),
    ]
