# Generated by Django 5.0.7 on 2024-08-07 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('agreement', 'Agreement'), ('deed', 'Deed'), ('inspection_report', 'Inspection Report'), ('insurance_policy', 'Insurance Policy')], max_length=50)),
                ('file_path', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('access_permissions', models.JSONField(default=dict)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ESignatureIntegration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('signature_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_log', models.JSONField(default=list)),
                ('signing_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_management.propertydocument')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_management.propertydocument')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSharing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('access_permissions', models.JSONField(default=dict)),
                ('activity_log', models.JSONField(default=list)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_management.propertydocument')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentExpirationReminder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reminder_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], default='pending', max_length=50)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_management.propertydocument')),
            ],
        ),
    ]
