# Generated by Django 5.0.7 on 2024-08-10 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reminder_alter_property_type'),
        ('document_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentexpirationreminder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='documentexpirationreminder',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='documentexpirationreminder',
            name='status',
        ),
        migrations.AddField(
            model_name='documentexpirationreminder',
            name='reminder_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.reminder'),
            preserve_default=False,
        ),
    ]
