# Generated by Django 5.0.7 on 2024-08-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentexpirationreminder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='esignatureintegration',
            name='signature_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
