# Generated by Django 5.0.7 on 2024-08-21 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_management', '0001_initial'),
        ('core', '0001_initial'),
        ('remote_property_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientForecastingService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('demand_forecasting_models', models.JSONField()),
                ('pricing_algorithms', models.JSONField()),
                ('report_templates', models.JSONField()),
                ('client_dashboard', models.JSONField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.client')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialDemand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leasing_data', models.JSONField()),
                ('market_trends', models.JSONField()),
                ('demand_forecast', models.JSONField()),
                ('tenant_profiles', models.JSONField()),
                ('lease_optimization', models.JSONField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('historical_data_sources', models.JSONField()),
                ('market_trends', models.JSONField()),
                ('demand_patterns', models.JSONField()),
                ('pricing_trends', models.JSONField()),
                ('forecast_results', models.JSONField()),
                ('scenario_analyses', models.JSONField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='DevelopmentFeasibility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('market_research', models.JSONField()),
                ('economic_models', models.JSONField()),
                ('demand_drivers', models.JSONField()),
                ('consumer_preferences', models.JSONField()),
                ('feasibility_results', models.JSONField()),
                ('sensitivity_analysis', models.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_property_monitoring.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='MarketDemand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_data', models.JSONField()),
                ('listing_inventory', models.JSONField()),
                ('market_indicators', models.JSONField()),
                ('demand_forecast', models.JSONField()),
                ('visualization_tools', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
